// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf-m0zUZX02kDblpeBz5C1PYjDgmTq1sU',
    appId: '1:229880053369:web:f71d7c75273f2fc12fdea8',
    messagingSenderId: '229880053369',
    projectId: 'ticketing-app-40407',
    authDomain: 'ticketing-app-40407.firebaseapp.com',
    storageBucket: 'ticketing-app-40407.firebasestorage.app',
    measurementId: 'G-1VKMP2EPEF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcWm7Mdc8xvyBv23PkiqFKXkaLoERx4aM',
    appId: '1:229880053369:android:45fe798447abb9ec2fdea8',
    messagingSenderId: '229880053369',
    projectId: 'ticketing-app-40407',
    storageBucket: 'ticketing-app-40407.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQmH4ZwqFnN-4yum_7aaekHlx4JJVeY0M',
    appId: '1:229880053369:ios:1be41ed82daa318c2fdea8',
    messagingSenderId: '229880053369',
    projectId: 'ticketing-app-40407',
    storageBucket: 'ticketing-app-40407.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQmH4ZwqFnN-4yum_7aaekHlx4JJVeY0M',
    appId: '1:229880053369:ios:1be41ed82daa318c2fdea8',
    messagingSenderId: '229880053369',
    projectId: 'ticketing-app-40407',
    storageBucket: 'ticketing-app-40407.firebasestorage.app',
    iosBundleId: 'com.example.flutterProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDf-m0zUZX02kDblpeBz5C1PYjDgmTq1sU',
    appId: '1:229880053369:web:1b62bb3d4af957c02fdea8',
    messagingSenderId: '229880053369',
    projectId: 'ticketing-app-40407',
    authDomain: 'ticketing-app-40407.firebaseapp.com',
    storageBucket: 'ticketing-app-40407.firebasestorage.app',
    measurementId: 'G-4HJLPN2YXK',
  );

}